### ISSUE TITLE
Problemi analisi

### ISSUE THREAD

**Issue by AlexMike-maker** [italia/pa-website-validator-gui#3]
Riscontriamo problemi con l'analisi di siti fatti in Plone.

`            {
  _: [
    '/Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/dist/commands/scan'
  ],
  type: 'municipality',
  destination: '/Users/<user>/Library/Application Support/pa-website-validator-ng-gui/db/reports/b4dc7d52-356c-43c0-a867-96c92c675c66',
  report: 'report',
  website: '<url_sito>',
  scope: 'online',
  accuracy: 'all',
  concurrentPages: 10,
  'concurrent-pages': 10,
  timeout: 30000,
  auditsSubset: 'municipality_font',
  'audits-subset': 'municipality_font',
  '$0': 'Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Frameworks/DTD-AppDiValutazione Helper.app/Contents/MacOS/DTD-AppDiValutazione Helper'
}
/Users/<user>/Library/Application Support/pa-website-validator-ng-gui/db/reports/b4dc7d52-356c-43c0-a867-96c92c675c66
AUDIT MANAGER registered audit: municipality_font
GATHERER MANAGER registered gatherer: vivere_page
GATHERER MANAGER registered gatherer: services_page
GATHERER MANAGER registered gatherer: services
GATHERER MANAGER registered gatherer: second_level_pages
GATHERER MANAGER registered gatherer: personal_area_login
GATHERER MANAGER registered gatherer: first_level_pages
GATHERER MANAGER registered gatherer: events_page
GATHERER MANAGER registered gatherer: events
GATHERER MANAGER registered gatherer: booking_appointment
Initializing Puppeteer Instance..
12/2/2024 11:13:56 AM SCAN  homepage  <url_sito>: Gathering start
<url_sito> goto tentative: 0
<url_sito> goto tentative: 1
<url_sito> goto tentative: 2
ERROR LOADPAGE FUNCTION <url_sito>: TimeoutError: Navigation timeout of 300000 ms exceeded
12/2/2024 11:33:56 AM  navigating Error gatherer = Error: Navigation timeout of 300000 ms exceeded
    at loadPage (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/utils/utils.js:92:19)
    at async scan (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/Scan.js:49:28)
    at async EventEmitter.<anonymous> (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/launchScript.js:47:13)
12/2/2024 11:33:56 AM SCAN  homepage  <url_sito>: ERROR
12/2/2024 11:33:56 AM  navigating Error gatherer = Error: Navigation timeout of 300000 ms exceeded
    at loadPage (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/utils/utils.js:92:19)
    at async scan (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/Scan.js:49:28)
    at async EventEmitter.<anonymous> (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/launchScript.js:47:13)
12/2/2024 11:33:56 AM SCAN  homepage  <url_sito>: ERROR
12/2/2024 11:33:56 AM  navigating Error gatherer = Error: Navigation timeout of 300000 ms exceeded
    at loadPage (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/utils/utils.js:92:19)
    at async scan (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/Scan.js:49:28)
    at async EventEmitter.<anonymous> (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/launchScript.js:47:13)
12/2/2024 11:33:56 AM SCAN [32m homepage[0m  <url_sito>: ERROR
12/2/2024 11:33:56 AM SCAN [32m services-page[0m  https://temppagenotavailable/Listato servizi: Gathering start
12/2/2024 11:33:56 AM  navigating Error gatherer = Error: Navigation timeout of 300000 ms exceeded
    at loadPage (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/utils/utils.js:92:19)
    at async scan (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/Scan.js:49:28)
    at async EventEmitter.<anonymous> (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/launchScript.js:47:13)
12/2/2024 11:33:56 AM SCAN  homepage  <url_sito>: ERROR
12/2/2024 11:33:56 AM SCAN  services-page  https://temppagenotavailable/Listato servizi: ERROR
12/2/2024 11:33:56 AM SCAN  vivere-page  https://temppagenotavailable/Vivere il comune: Gathering start
12/2/2024 11:33:56 AM  navigating Error gatherer = Error: Navigation timeout of 300000 ms exceeded
    at loadPage (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/utils/utils.js:92:19)
    at async scan (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/Scan.js:49:28)
    at async EventEmitter.<anonymous> (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/launchScript.js:47:13)
12/2/2024 11:33:56 AM SCAN  homepage  <url_sito>: ERROR
12/2/2024 11:33:56 AM SCAN  services-page  https://temppagenotavailable/Listato servizi: Gathering end
12/2/2024 11:33:56 AM SCAN [32m vivere-page[0m  https://temppagenotavailable/Vivere il comune: ERROR
12/2/2024 11:33:56 AM  navigating Error gatherer = Error: Navigation timeout of 300000 ms exceeded
    at loadPage (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/utils/utils.js:92:19)
    at async scan (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/Scan.js:49:28)
    at async EventEmitter.<anonymous> (file:///Users/<user>/Downloads/DTD-AppDiValutazione.app/Contents/Resources/node_modules/pa-website-validator-ng/dist/launchScript.js:47:13)
12/2/2024 11:33:56 AM SCAN  homepage  <url_sito>: ERROR
12/2/2024 11:33:56 AM SCAN  vivere-page  https://temppagenotavailable/Vivere il comune: Gathering end
12/2/2024 11:33:56 AM SCAN  personal-area-login  https://temppagenotavailable/Login area personale: Auditing start
12/2/2024 11:33:56 AM SCAN  homepage  <url_sito>: Gathering end
12/2/2024 11:33:56 AM SCAN [32m homepage[0m  <url_sito>: Auditing start
12/2/2024 11:33:56 AM SCAN [32m service[0m  https://temppagenotavailable/Servizio: Auditing start
12/2/2024 11:33:56 AM SCAN  first-level-page  https://temppagenotavailable/Pagina di primo livello: Auditing start
12/2/2024 11:33:56 AM SCAN  events-page  https://temppagenotavailable/Pagina eventi: Gathering start
12/2/2024 11:33:56 AM SCAN  events-page  https://temppagenotavailable/Pagina eventi: ERROR
12/2/2024 11:33:56 AM SCAN  personal-area-login  https://temppagenotavailable/Login area personale: Auditing end
12/2/2024 11:33:56 AM SCAN [32m second-level-page[0m  https://temppagenotavailable/Pagina di secondo livello: Auditing start
12/2/2024 11:33:56 AM SCAN  service  https://temppagenotavailable/Servizio: Auditing end
12/2/2024 11:33:56 AM SCAN [32m events-page[0m  https://temppagenotavailable/Pagina eventi: Gathering end
12/2/2024 11:33:56 AM SCAN  first-level-page  https://temppagenotavailable/Pagina di primo livello: Auditing end
12/2/2024 11:33:56 AM SCAN [32m second-level-page[0m  https://temppagenotavailable/Pagina di secondo livello: Auditing end
<url_sito> goto tentative: 0
<url_sito> goto tentative: 1
<url_sito> goto tentative: 2
ERROR LOADPAGE FUNCTION <url_sito>: TimeoutError: Navigation timeout of 300000 ms exceeded
12/2/2024 11:53:56 AM SCAN  homepage  <url_sito>: Auditing end
12/2/2024 11:53:56 AM SCAN ENDED - navigated pages end: <url_sito> homepage
closing puppeteer
Execution time: 2400889
          `
          
Il problema si presenta sui dispositivi : mac, linux, e windows.

**Comment by AlexMike-maker** [comment]
Nessun riscontro?
